### ISSUE TITLE
error msg when launching 'ruby shocens.rb'

### ISSUE THREAD

**Issue by syrius01** [thesubtlety/shocens#3]
Hi !

This tool looks awesome, good idea of combining shodan + censys :) Here's the error msg I get when I launch 'ruby shocens.rb' for the first time;

sirius@blackb0x:~/censys/shocens$ ruby shocens.rb
/home/sirius/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- shodan (LoadError)
        from /home/sirius/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from shocens.rb:22:in `<main>'

I have shodan installed on my Ubuntu.

Thank you for your time

**Comment by bcoles** [comment]
You're missing the `shodan` dependency.

```bash
gem install ruby_dig shodan rest-client
```
